apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mongo-logs
spec:
  type: state.mongodb
  version: v1
  metadata:
  - name: server
    value: "discovercostarica.mongocluster.cosmos.azure.com"
  - name: username
    value: "tico"
  - name: password
    secretKeyRef:
          name: mongo-pass
          key: mongo-pass
  - name: databaseName
    value: "discovercostarica"               
  - name: collectionName
    value: "logs"          
  - name: params
    value: "?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000"
auth:
  secretStore: local-secret-store