// <auto-generated />
using DiscoverCostaRica.Geo.Infraestructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiscoverCostaRica.Geo.Infrastructure.Migrations
{
    [DbContext(typeof(GeoContext))]
    partial class GeoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiscoverCostaRica.Geo.Domain.Models.CantonModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Geo.Canton", (string)null);
                });

            modelBuilder.Entity("DiscoverCostaRica.Geo.Domain.Models.DistrictModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CantonId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CantonId");

                    b.ToTable("Geo.District", (string)null);
                });

            modelBuilder.Entity("DiscoverCostaRica.Geo.Domain.Models.ProvinceModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Geo.Province", (string)null);
                });

            modelBuilder.Entity("DiscoverCostaRica.Geo.Domain.Models.CantonModel", b =>
                {
                    b.HasOne("DiscoverCostaRica.Geo.Domain.Models.ProvinceModel", "Province")
                        .WithMany("Cantons")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("DiscoverCostaRica.Geo.Domain.Models.DistrictModel", b =>
                {
                    b.HasOne("DiscoverCostaRica.Geo.Domain.Models.CantonModel", "Canton")
                        .WithMany("Districts")
                        .HasForeignKey("CantonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Canton");
                });

            modelBuilder.Entity("DiscoverCostaRica.Geo.Domain.Models.CantonModel", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("DiscoverCostaRica.Geo.Domain.Models.ProvinceModel", b =>
                {
                    b.Navigation("Cantons");
                });
#pragma warning restore 612, 618
        }
    }
}
