global using static DiscoverCostaRica.Shared.Utils.SharedExtensions;
global using static DiscoverCostaRica.Generated.ServiceRegistrationExtensions_DiscoverCostaRica_Beaches_Application;
global using static DiscoverCostaRica.Generated.ServiceRegistrationExtensions_DiscoverCostaRica_Beaches_Infraestructure;